### ISSUE TITLE
Is there any update for PHP 8.1?

### ISSUE THREAD

**Issue by iceleo-com** [Vonage/vonage-php-sdk-core#298] opened 2021-12-06 02:29 UTC
Hello Sir/Ma'am,

Hope you are well!

I have upgraded my system to PHP 8.1. I get a new error report.
Is there any new plan for upgrading the code to be compatible with PHP 8.1 sir/ma'am?

This is the error that I got after upgrading to PHP 8.1:

`PHP Unknown:  Return type of Vonage\Client\Credentials\AbstractCredentials::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vonage/client-core/src/Client/Credentials/AbstractCredentials.php on line 31`

The version of **Vonage Client** that I'm using is **2.4**

Thank you so much for reviewing my question

**Comment by SecondeJK** [comment] 2021-12-06 13:59
Hi @iceleo-com, we're currently looking at the roadmap for this library which will likely change due to the change in maintainer/ownership. One of the items on my to-do list is PHP8.1 support, but not sure when this will arrive, I'll keep you posted.

**Comment by iceleo-com** [comment] 2021-12-06 14:57
Hi @SecondeJK ,

Thank you for your response.

Currently, I can tweak the code a little to make it work. Nothing urgent, it still works. I will let you know if I get a serious problem and cannot solve it by myself.

**Comment by SecondeJK** [comment] 2022-01-10 11:35
Hi @iceleo-com, just as an update to this while I am trying to get some major deprecations out of the codebase - 
Currently running the latest release (2.10.0) of this library will work with PHP8.1 although it will still show you the depreciation warnings. Is the error you're getting actually stopping runtime, or is it just a warning?

**Comment by BafS** [comment] 2022-01-11 11:31
I think the issue is that many projects will treat deprecations as exceptions.

Adding `#[\ReturnTypeWillChange]` on top of the method(s) should make it compatible with PHP 8.1 without breaking anything.

**Comment by SecondeJK** [comment] 2022-01-18 12:50
This will be fixed with PR #301 when merged to main, and released as 3.0.0. It's a temporary solution, as noted in the PHP docs on this anyway, but that doesn't matter too much as these methods are marked for removal eventually anyway

**Comment by SecondeJK** [comment] 2022-01-26 11:16
Fixed in #209

**Closed by SecondeJK** 2022-01-26 11:16 UTC
Labels: request

**Comment by BafS** [comment] 2022-01-26 21:10
Thank you! (I think you meant in https://github.com/Vonage/vonage-php-sdk-core/pull/301)

**Comment by SecondeJK** [comment] 2022-01-27 09:01
Whoops! Hah sorry I meant to add the tag yes
